name: "Your name"
picture: "assets/img/picture.jpg"
bio: "DevOps engineer, creator and problem solver"
meta:
  lang: "ru"
  description: "Personal link page"
  title: "Your name"
  author: "Your name"
  siteUrl: "https://username.github.io/taplink/"
links:
  - name: "Telegram"
    url: "https://t.me/username"
  - name: "GitHub"
    url: "https://github.com/username"
  - name: "Email"
    url: "mailto:hello@example.com"
theme: "custom"
